[package]
name = "site"
version = "0.1.0"
authors = ["Jorge Israel Peña <jorge.israel.p@gmail.com>"]

[dependencies]
toml = "*"
glob = "*"
typemap = "*"
time = "*"
log = "*"
env_logger = "*"
rustc-serialize = "*"
hoedown = "*"
zmq = "*"
regex = "*"

[dependencies.diecast]
path = "../diecast"

[dependencies.diecast_websocket]
path = "../websocket"

[dependencies.diecast_git]
path = "../git"

[dependencies.diecast_rss]
path = "../rss"

[dependencies.diecast_scss]
path = "../scss"

[dependencies.diecast_handlebars]
path = "../handlebars"

