baseURL = "https://www.jip.dev/"
languageCode = "en-us"
title = "Jorge Israel Peña"

theme = "jip"

enableGitInfo = true
pygmentsCodeFences = true
pygmentsUseClasses = true
FootnoteReturnLinkContents = '<i class="fas fa-level-up-alt"></i>'

[blackfriday]
fractions = false

[taxonomies]
category = "categories"
tag = "tags"