baseURL = "https://www.jip.dev/"
languageCode = "en-us"
title = "Jorge Israel Peña"

theme = "jip"
rssLimit = 20

enableGitInfo = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[blackfriday]
fractions = false

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[markup.goldmark.parser]
attribute = true
autoHeadingID = true
autoHeadingIDType = "github"

[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xHTML = false