[diecast]
ignore = '^\.|^#|~$|\.swp$|4913'

[diecast.command.live]
address = "0.0.0.0:3000"

[diecast.handler.websocket]
address = "0.0.0.0:9160"

# hypothetical future
# [[diecast.rule]]
# name = "posts"
# dependencies = [ "templates" ]
# pattern = "posts/*.markdown"
# recipe = "content"
